### ISSUE TITLE
Error in running psi4 job

### ISSUE THREAD

**Issue by jinmei-1** [arwalkerlab/AutoParams#3]
This tool is quite fascinating! While testing the AutoParamsCompound1.pdb as mentioned in your article, I encountered the following error:
Exiting to enable the execution of QM computations; the corresponding commands can be found in /home/jinmei2/program/autoparams/AutoParams-main/Application/uploads/ab77cd81d96f493fa1efa8b0bf5359cb/single_point/run_single_point.sh
/bin/sh: 1: cannot create /app/PsiRESP.out: Directory nonexistent
I installed AutoParams using the conda method, and after performing the command cp -r Application app, the app folder already exists.
![image](https://github.com/arwalkerlab/AutoParams/assets/134991066/1d83435b-6038-4ba8-ac69-a1a7f09fea20)
![image](https://github.com/arwalkerlab/AutoParams/assets/134991066/dbdb1172-8383-4da8-a40b-8d42b2432ee0)
![image](https://github.com/arwalkerlab/AutoParams/assets/134991066/adcf25cd-4f97-450e-a990-ab8bbe32a9e6)
![image](https://github.com/arwalkerlab/AutoParams/assets/134991066/6894f95c-8d0a-460f-ade7-af48c07722ac)
We appreciate your assistance and look forward to your guidance. Meanwhile, we are sharing output file with you for a better understanding of our issues.Thank you for your time and support. We eagerly await your response.
[ab77cd81d96f493fa1efa8b0bf5359cb.zip](https://github.com/arwalkerlab/AutoParams/files/13849139/ab77cd81d96f493fa1efa8b0bf5359cb.zip)

**Comment by walkerar** [comment]
@markahix is currently working on a fix for this! In the meantime, you can use the Docker containers.

**Comment by markahix** [comment]
Thanks for bringing this to my attention!  I originally wrote the Psi4/PsiRESP handling with the idea that it would be used inside the Docker Container, and therefore I relied on the internal filesystem heirarchy of the base image.  However, for those who are using the code on a local machine, the file path assumptions I made were no longer valid.  As such, I've rearranged where the mid-stage output files are kept so that no additional permissions are required.

I've tested this change and was able to get it to run to completion without complaining about any file permissions, so I'm going to close this issue.
